[package]
name = "day-17"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = {workspace = true}
log = {workspace = true}
priority-queue = "1.3.2"

[features]
default = []
debug = []
